version: 0.2

env:
   parameter-store:
    ssh_key: id_ed25519 
    ssh_pub: id_ed25519.pub

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_ed25519
      - echo "$ssh_pub" > ~/.ssh/id_ed25519.pub
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git submodule init
      - git submodule update --recursive
  build:
    commands:
      - python3.8 submodule_caller.py
      - echo '...replace with real build commands...'

artifacts: 
  files: 
    - '**/*'
